#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: https://genkiroid.github.io
baseurl: ""
title: /etc/motg
description: genkiroid's blog about web application engineering.
# avatar: https://avatars2.githubusercontent.com/u/1169623?v=3&s=460
favicon: /assets/img/ogp.png
language: ja

# Twitter card
twitter:
  username: genkiroid

#
# Icons
#
icons:
  rss: true
  email: gamurai@gmail.com
  github: genkiroid
  bitbucket:
  twitter: genkiroid
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: # full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: # e.g. UA-000000-01
# disqus: genkiroid

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: true
  facebook: false # needs ogp.fb.app_id
  hatena: true
ogp:
  image_url: //ttskch.github.io/jekyll-tch-theme/assets/img/ogp.png
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
