version: "3.9"
services:
  jekyll:
    platform: linux/amd64
    image: jekyll/jekyll:latest
    command: jekyll serve --trace --force_polling
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - "4000:4000"
